from os import PathLike
from typing import TypeAlias

__version__: str

TensorData: TypeAlias = float | list[TensorData] | tuple[TensorData, ...]

class Tensor:
    def __init__(self, data: TensorData, *, requires_grad: bool = False) -> None: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def ndim(self) -> int: ...
    @property
    def numel(self) -> int: ...
    @property
    def dtype(self) -> str: ...
    @property
    def requires_grad(self) -> bool: ...
    @property
    def is_leaf(self) -> bool: ...
    @property
    def grad(self) -> Tensor | None: ...
    def tolist(self) -> list[object]: ...
    def item(self) -> float: ...
    def detach(self) -> Tensor: ...
    def zero_grad(self) -> None: ...
    def backward(self) -> None: ...
    def mean(self) -> Tensor: ...
    def __add__(self, other: Tensor) -> Tensor: ...
    def __sub__(self, other: Tensor) -> Tensor: ...
    def __mul__(self, other: Tensor) -> Tensor: ...
    def __truediv__(self, other: Tensor) -> Tensor: ...
    def __matmul__(self, other: Tensor) -> Tensor: ...
    def __neg__(self) -> Tensor: ...

class Session:
    def __init__(self, path: str | PathLike[str], *, simplify: bool = True) -> None: ...
    @property
    def inputs(self) -> list[str]: ...
    @property
    def outputs(self) -> list[str]: ...
