from os import PathLike

from typing_extensions import TypeAlias

__version__: str

TensorData: TypeAlias = float | list["TensorData"] | tuple["TensorData", ...]
ReductionDim: TypeAlias = int | tuple[int, ...]

class _NoGrad:
    def __enter__(self) -> None: ...
    def __exit__(self, exception_type: object, exception: object, traceback: object) -> bool: ...

def no_grad() -> _NoGrad: ...
def is_grad_enabled() -> bool: ...

class Tensor:
    def __init__(self, data: TensorData, *, requires_grad: bool = False) -> None: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def ndim(self) -> int: ...
    @property
    def numel(self) -> int: ...
    @property
    def dtype(self) -> str: ...
    @property
    def requires_grad(self) -> bool: ...
    @property
    def is_leaf(self) -> bool: ...
    @property
    def grad(self) -> Tensor | None: ...
    def tolist(self) -> list[object]: ...
    def item(self) -> float: ...
    def detach(self) -> Tensor: ...
    def zero_grad(self) -> None: ...
    def backward(self, gradient: Tensor | None = None) -> None: ...
    def sum(self, dim: ReductionDim | None = None, keepdim: bool = False) -> Tensor: ...
    def mean(self, dim: ReductionDim | None = None, keepdim: bool = False) -> Tensor: ...
    def __add__(self, other: Tensor) -> Tensor: ...
    def __sub__(self, other: Tensor) -> Tensor: ...
    def __mul__(self, other: Tensor) -> Tensor: ...
    def __truediv__(self, other: Tensor) -> Tensor: ...
    def __matmul__(self, other: Tensor) -> Tensor: ...
    def __neg__(self) -> Tensor: ...

class Parameter(Tensor):
    def __init__(self, data: TensorData, *, name: str | None = None) -> None: ...
    @property
    def name(self) -> str | None: ...

class Session:
    def __init__(self, path: str | PathLike[str], *, simplify: bool = True) -> None: ...
    @property
    def inputs(self) -> list[str]: ...
    @property
    def outputs(self) -> list[str]: ...
